### ISSUE TITLE
Consider adding documentations explaining multiple directories for assets

### ISSUE THREAD

**Issue by sraby** [JustFixNYC/tenants2#1065]
Currently we store assets in a [static / frontent folder](https://github.com/JustFixNYC/tenants2/tree/master/frontend/static/frontend/img) as well as an [svg folder](https://github.com/JustFixNYC/tenants2/tree/master/frontend/lib/svg). Consider merging these two directories?

**Comment by toolness** [comment]
Oh, so this is kind of weird because the assets are bundled in different ways... everything in `static/frontend` is really intended to be referenced by URL, e.g. `<img src="some/frontend/asset.png">` while the stuff in `frontend/lib/svg` is intended to be inlined into the actual JS bundle (I believe this is how Create React App does things).

I totally understand the confusion though, and I'm not sure what the best way to address it is ... especially since I think webpack and/or TypeScript might get upset if the assets to be inlined are outside of the `frontend/lib` directory, while assets outside of `frontend/static` won't actually be copied to s3, where all the static assets that are linked-to via URL need to live... Oy!

At the very least we should intelligibly document the current state of affairs, but if we can figure out a way to make things more obvious that would be great too.  One really simple thing we could do is rename `frontend/lib/svg` to `frontend/lib/svgs-to-inline`, just to make it clear what that's for... hmm.

**Comment by sraby** [comment]
Oh good to know! Seems like this isn't priority right now so I renamed the issue for us to come back to

**Comment by toolness** [comment]
This is now documented in our wiki dev guide at https://github.com/JustFixNYC/tenants2/wiki/Development-guide#images.
