### ISSUE TITLE
Lock down SMS content / structure

### ISSUE THREAD

**Issue by romeboards** [JustFixNYC/tenants2#274]
To discuss with Adalky on 10/15. What we landed on from the last conversation:

**On user signup:** *(assuming they have allowed texts)* Welcome to JustFix.nyc! We'll be sending you notifications from this phone number.

**On letter completion / justfix mailing:** JustFix.nyc here - we've received your request and will update you once the letter has been sent. Please allow for 1-2 business days to process.

**Comment by toolness** [comment]
Um, so something I'm realizing here is that if they are on a desktop/laptop for signup and they opt _not_ to enter a password, and then they tap the link on their phone, they won't actually be able to log in, because they're on a completely different browser.

The same might actually apply if they e.g. found out about JustFix on Facebook, using its embedded browser, which may have a completely different session state from their phone's primary browser (which is the one that'd be opened if they tapped on the link in their text message).

Some solutions/workarounds:

1. Only send the link if they've also entered a password.

2. Add some kind of nonce to the link that automatically logs them in when they visit it.  This is nontrivial to implement, though, and we'd have to carefully consider its security implications.  That said, it could double as the solution for some kind of passwordless login (#170).

3. Reword the first message so users know that the link is a "backup" and should only visit it if they somehow lose track of the browser page they're currently on.  (In other words, users shouldn't actually move off our site as a result of getting the text message.)

**Comment by toolness** [comment]
Fixed by 607c545.
